version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"